Split into jobs, add more checks

diff --git a/.github/workflows/ensure-stage-before-merge.yml b/.github/workflows/ensure-stage-before-merge.yml
--- a/.github/workflows/ensure-stage-before-merge.yml
+++ b/.github/workflows/ensure-stage-before-merge.yml
@@ -7,7 +7,7 @@ on:
       - 'text/*.md'
 
 jobs:
-  check-labels:
+  check-in-exploring:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -22,6 +22,68 @@ jobs:
       - name: Ensure the RFC is in the Exploring Stage before merge is allowed
         if: steps.rfcs.outputs.added_files && !contains(github.event.pull_request.labels.*.name, 'S-Exploring')
         run: |
-          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
-          echo "RFCs must advance to the Exploring Stage before merging to Accepted is allowed"
+          echo "Newly added RFCs must advance to the Exploring Stage before merging to Accepted is allowed"
           exit 1
+
+  verify-only-in-one-stage:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Find added or modified RFCs
+        id: rfcs
+        uses: tj-actions/changed-files@v25
+        with:
+          path: 'text'
+          json: 'true'
+
+      - name: Ensure the RFC only has one stage
+        if: steps.rfcs.outputs.added_files && contains(github.event.pull_request.labels.*.name, 'S-Exploring') && contains(github.event.pull_request.labels.*.name, 'S-Proposed')
+        run: |
+          echo "Newly added RFCs must only have one stage label"
+          exit 1
+
+  only-one-rfc-added:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Find added or modified RFCs
+        id: rfcs
+        uses: tj-actions/changed-files@v25
+        with:
+          path: 'text'
+          json: 'true'
+
+      - name: Fail if more than 1 RFC is added
+        if: steps.rfcs.outputs.added_files
+        run: |
+          len=`echo "${{ steps.rfcs.outputs.added_files }}" | jq '. | length'`
+          echo "RFCs added or modified: ${{ steps.rfcs.outputs.added_files }}"
+          if [[ $len > 1 ]]; then
+            echo "::error::More than 1 RFC is added in this PR; will be unable to automatically open PRs for advancement"
+            exit 1
+          fi
+
+  frontmatter-stage-is-accepted:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Find added or modified RFCs
+        id: rfcs
+        uses: tj-actions/changed-files@v25
+        with:
+          path: 'text'
+          json: 'true'
+
+      - name: Verify stage of newly added RFC is `accepted` in frontmatter
+        if: steps.rfcs.outputs.added_files
+        run: |
+          added_rfc=`echo "${{ steps.rfcs.outputs.added_files }}" | jq '.[0]'` 
+          frontmatter=`node rfcs-tooling/rfc-frontmatter.js "$added_rfc"`
+          stage=`echo $frontmatter | jq '.stage'`
+          if [[ $stage != '"accepted"' ]]; then
+              echo "::error::Newly added RFCs must have the stage 'accepted' in the frontmatter"
+              exit 1
+          fi
