Add check for prs.accepted

diff --git a/.github/workflows/newly-added-rfc.yml b/.github/workflows/newly-added-rfc.yml
--- a/.github/workflows/newly-added-rfc.yml
+++ b/.github/workflows/newly-added-rfc.yml
@@ -103,3 +103,24 @@ jobs:
           PR_NUMBER: ${{ github.event.pull_request.number }}
         run: node check-filename-matches-pr.js $PR_NUMBER ${{ needs.check-rfcs.outputs.modified-rfc }}
         working-directory: rfcs-tooling
+
+  check-accepted-pr-url:
+    name: Verify Accepted PR URL is correct
+    runs-on: ubuntu-latest
+    needs: [ check-rfcs ]
+    if: needs.check-rfcs.outputs.rfcs-added == 'true'
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Setup RFCs tooling
+        uses: ./.github/actions/setup-rfcs-tooling
+
+      - name: Verify Accepted PR URL is correct
+        run: |
+          frontmatter=`node rfcs-tooling/rfc-frontmatter.js ${{ needs.check-rfcs.outputs.modified-rfc }}`
+          accepted_pr=`echo $frontmatter | jq '.prs.accepted'`
+          accepted_pr=${accepted_pr//\"/}
+          if [[ $accepted_pr != {{ github.event.pull_request.url }} ]]; then
+              echo "::error::Accepted PR URL is incorrect, please update the frontmatter prs.accepted to \"{{ github.event.pull_request.url }}\""
+              exit 1
+          fi
