fixup

diff --git a/.github/workflows/newly-added-rfc.yml b/.github/workflows/newly-added-rfc.yml
--- a/.github/workflows/newly-added-rfc.yml
+++ b/.github/workflows/newly-added-rfc.yml
@@ -120,7 +120,7 @@ jobs:
           frontmatter=`node rfcs-tooling/rfc-frontmatter.js ${{ needs.check-rfcs.outputs.modified-rfc }}`
           accepted_pr=`echo $frontmatter | jq '.prs.accepted'`
           accepted_pr=${accepted_pr//\"/}
-          if [[ $accepted_pr != {{ github.event.pull_request.url }} ]]; then
-              echo "::error::Accepted PR URL is incorrect, please update the frontmatter prs.accepted to \"{{ github.event.pull_request.url }}\""
-              exit 1
+          if [[ $accepted_pr != ${{ github.event.pull_request.url }} ]]; then
+            echo "::error::Accepted PR URL is incorrect, please update the frontmatter prs.accepted to \"{{ github.event.pull_request.url }}\""
+            exit 1
           fi
